services:
  django-test:
    container_name: django_test
    build:
      context: ./django_project
      dockerfile: Dockerfile-test
    volumes:
      - .:/django_project
    depends_on:
      redis-test:
        condition: service_healthy
    command: ["pytest", "--rootdir=/django_project"]
    environment:
      - REDIS_HOST=redis-test
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app_network

  redis-test:
    container_name: redis-container-test
    build:
      context: ./redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 2
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: