services:
  django-test:
    container_name: django_test
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/django_project
    env_file:
      - .env.test
    depends_on:
      - redis
    command: ["pytest"]

  redis-test: # best practice
    container_name: redis-container-test
    build:
      context: ./redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 2
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app_network
