services:
  django-test:
    container_name: django_test
    build:
      context: ./django_project
      dockerfile: Dockerfile-test
    volumes:
      - .:/django_project
    depends_on:
      redis-test:
        condition: service_healthy
    command: >
      sh -c "
      python manage.py makemigrations --check &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      sleep 2 &&
      python manage.py runserver 0.0.0.0:8000 &&
      sleep 10 &&
      pytest"
    expose:
      - "8000"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CACHE_TTL=${REDIS_CACHE_TTL}
      - DOMAIN_FOR_FAKE_URL=${DOMAIN_FOR_FAKE_URL}
    networks:
      - app_network

  redis-test:
    container_name: redis-container-test
    build:
      context: ./redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 2
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: