# Generated by Django 5.1.3 on 2024-11-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="salt",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
