# Generated by Django 5.1.3 on 2024-12-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_app", "0003_alter_usermodel_options_alter_usermodel_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="salt",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="custom_permission_set", to="auth.permission"
            ),
        ),
    ]
