# Generated by Django 5.1.3 on 2024-12-01 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger_app", "0002_rename_fake_url_loggermodel_destination_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggermodel",
            options={"verbose_name": "Logger", "verbose_name_plural": "Loggers"},
        ),
        migrations.AddField(
            model_name="loggermodel",
            name="fake_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loggermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
